name: example-environment
channels:
  - conda-forge
dependencies:
  - python
  - nodejs
  - pyspice
  - ngspicesimserver>=0.3.3
  - pycapnp
  - jupyter
  - jupyter_bokeh
  - bokeh
  - pip
  - pip:
    - Pyttoresque>=0.3.3
