# SPDX-FileCopyrightText: 2022 Pepijn de Vos
#
# SPDX-License-Identifier: MPL-2.0

name: example-environment
channels:
  - conda-forge
dependencies:
  - pyspice
  - jupyterlab-mosaic
  - ngspicesimserver>=0.4.1
  - pyttoresque>=0.4.2
