# SPDX-FileCopyrightText: 2022 Pepijn de Vos
#
# SPDX-License-Identifier: MPL-2.0

name: example-environment
channels:
  - conda-forge
  - litex-hub
dependencies:
  - pyttoresque>=1.0.2
  - ngspicesimserver>=0.4.3
  - jupyterlab-mosaic
  - pyspice
  - open_pdks.sky130a
  - dask # something depends on dask-core and then complains distribute is missing
